LAB_DESCRIPTION="First test of vulnerability - Apache CXF SSRF"

m1[0]="A/00:00:00:00:00:01"
m1[image]="kathara/base"
m1[ipv6]="false"

m2[0]="A/00:00:00:00:00:02"
m2[image]="cxf-iproute"
m2[ipv6]="false"

wireshark[0]=A
wireshark[bridged]=true
wireshark[port]="3000:3000"
wireshark[image]="lscr.io/linuxserver/wireshark"
wireshark[num_terms]=0
