LAB_DESCRIPTION="Network Analysis - Type 1 (10 machines, 3 routers, 6 domains)"

pc1[0]="C/00:00:00:00:00:01"
pc1[image]="kathara/base-python3-nmap3"
pc1[ipv6]="false"

pc2[0]="C/00:00:00:00:00:02"
pc2[image]="vulhub/tomcat-tools"
pc2[ipv6]="false"

pc3[0]="C/00:00:00:00:00:03"
pc3[image]="kathara/apache"
pc3[ipv6]="false"

pc4[0]="A/00:00:00:00:00:04"
pc4[image]="vulhub/cups-tools"
pc4[ipv6]="false"

pc5[0]="A/00:00:00:00:00:05"
pc5[image]="kathara/base-telnet-ftp"
pc5[ipv6]="false"

pc6[0]="D/00:00:00:00:00:06"
pc6[image]="vulhub/redis-tools"
pc6[ipv6]="false"

pc7[0]="D/00:00:00:00:00:07"
pc7[image]="kathara/base-python3-nmap3"
pc7[ipv6]="false"

pc8[0]="D/00:00:00:00:00:08"
pc8[image]="kathara/base-postgresql"
pc8[ipv6]="false"

pc9[0]="E/00:00:00:00:00:09"
pc9[image]="kathara/bind"
pc9[ipv6]="false"

pc10[0]="E/00:00:00:00:00:10"
pc10[image]="kathara/base-python3-nmap3"
pc10[ipv6]="false"

r1[0]="A/00:00:00:00:00:a1"
r1[1]="B/00:00:00:00:00:b1"
r1[2]="C/00:00:00:00:00:c1"
r1[image]="kathara/base-python3-nmap3"
r1[ipv6]="false"

r2[0]="D/00:00:00:00:00:c1"
r2[1]="B/00:00:00:00:00:b2"
r2[2]="F/00:00:00:00:00:f1"
r2[bridged]=true
r2[image]="kathara/base-python3-nmap3"
r2[ipv6]="false"

r3[0]="E/00:00:00:00:00:e1"
r3[1]="F/00:00:00:00:00:f2"
r3[image]="kathara/base-python3-nmap3"
r3[ipv6]="false"

wireshark[bridged]=true
wireshark[port]="3000:3000"
wireshark[image]="lscr.io/linuxserver/wireshark"
wireshark[num_terms]=0
